# Generated by Django 3.1.2 on 2022-10-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20220930_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date_measure',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
