# Generated by Django 3.1.2 on 2022-10-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_auto_20221002_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='date_measure',
            new_name='created_at',
        ),
    ]
