# Generated by Django 3.1.2 on 2022-10-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_auto_20221002_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='SensorID',
            new_name='sensor',
        ),
    ]
