# Generated by Django 3.1.2 on 2022-10-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0010_auto_20221002_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='image',
        ),
    ]
