# Generated by Django 3.1.2 on 2022-10-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0011_remove_measurement_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
